### ISSUE TITLE
add separate columns for aligned taxon ranks and their ids 

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/name-alignment-template#14]
as suggested by @ljwalker and colleagues Chrissy and Christina - 

currently, alignedTaxonPath, alignedTaxonPathIds contains the entire hierarchy, pipe delimited. 

suggested keep the path columns and add individual columns for name/id pairs of commonly used taxonomic ranks (kingdom, phylum, etc).

example created by @ljwalker includes: 

![image](https://user-images.githubusercontent.com/1084872/221052386-e326a3db-ad96-4bd8-9802-e2f8f341d485.png)

**Comment by jhpoelen** [comment]
@ljwalker I made a first attempt to add the separate columns for aligned taxon ranks and their ids. Also, I left the path columns as suggested.

Can you please re-run your names and verify that the columns have been added as suggested? 

See example below .

alignedKingdomName | alignedKingdomId | alignedPhylumName | alignedPhylumId | alignedClassName | alignedClassId | alignedOrderName | alignedOrderId | alignedFamilyName | alignedFamilyId | alignedGenusName | alignedGenusId | alignedSubgenusName | alignedSubgenusId | alignedSpeciesName | alignedSpeciesId | alignedSubspeciesName | alignedSubspeciesId | alignedPath | alignedPathIds | alignedPathNames
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Fungi | NCBI:4751 | Basidiomycota | NCBI:5204 | Agaricomycetes | NCBI:155619 | Agaricales | NCBI:5338 | Agaricaceae | NCBI:5339 | Agaricus | NCBI:5340 |   |   | Agaricus bisporus | NCBI:5341 |   |   | \| Eukaryota \| Opisthokonta \| Fungi \| Dikarya \| Basidiomycota \| Agaricomycotina \| Agaricomycetes \| Agaricomycetidae \| Agaricales \| Agaricineae \| Agaricaceae \| Agaricus \| Agaricus bisporus | NCBI:131567 \| NCBI:2759 \| NCBI:33154 \| NCBI:4751 \| NCBI:451864 \| NCBI:5204 \| NCBI:5302 \| NCBI:155619 \| NCBI:452333 \| NCBI:5338 \| NCBI:2982305 \| NCBI:5339 \| NCBI:5340 \| NCBI:5341 | \| superkingdom \| clade \| kingdom \| subkingdom \| phylum \| subphylum \| class \| subclass \| order \| suborder \| family \| genus \| species
Fungi | OTT:352914 | Basidiomycota | OTT:634628 | Agaricomycetes | OTT:1012685 | Agaricales | OTT:8364 | Agaricaceae | OTT:8360 | Agaricus | OTT:737448 |   |   | Agaricus bisporus | OTT:564405 |   |   | \|  \| Eukaryota \| Opisthokonta \| Nucletmycea \| Fungi \|  \|  \| Dikarya \| Basidiomycota \| Agaricomycotina \| Agaricomycetes \| Agaricales \| Agaricaceae \| Agaricus \| Agaricus bisporus | OTT:805080 \| OTT:93302 \| OTT:304358 \| OTT:332573 \| OTT:5246132 \| OTT:352914 \| OTT:5576447 \| OTT:5584405 \| OTT:656316 \| OTT:634628 \| OTT:633300 \| OTT:1012685 \| OTT:8364 \| OTT:8360 \| OTT:737448 \| OTT:564405 | no rank \| no rank \| domain \| no rank \| no rank \| kingdom \| no rank \| no rank \| subkingdom \| phylum \| subphylum \| class \| order \| family \| genus \| species
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | Fungi \| Basidiomycota \| Agaricomycetes \| Agaricales \| Agaricaceae \| Agaricus bisporus |   | kingdom \| phylum \| class \| order \| family \|
Fungi | IRMNG:14 | Basidiomycota | IRMNG:236 | Agaricomycetes | IRMNG:1108 | Agaricales | IRMNG:10892 | Agaricaceae | IRMNG:110489 | Agaricus | IRMNG:1332778 |   |   | Agaricus bisporus | IRMNG:11209605 |   |   | Fungi \| Basidiomycota \| Agaricomycetes \| Agaricales \| Agaricaceae \| Agaricus \| Agaricus bisporus | IRMNG:14 \| IRMNG:236 \| IRMNG:1108 \| IRMNG:10892 \| IRMNG:110489 \| IRMNG:1332778 \| IRMNG:11209605 | kingdom \| phylum \| class \| order \| family \| genus \| species
Fungi | GBIF:5 | Basidiomycota | GBIF:34 | Agaricomycetes | GBIF:186 | Agaricales | GBIF:1499 | Agaricaceae | GBIF:4170 | Agaricus | GBIF:2518646 |   |   | Agaricus bisporus | GBIF:5243447 |   |   | Fungi \| Basidiomycota \| Agaricomycetes \| Agaricales \| Agaricaceae \| Agaricus \| Agaricus bisporus | GBIF:5 \| GBIF:34 \| GBIF:186 \| GBIF:1499 \| GBIF:4170 \| GBIF:2518646 \| GBIF:5243447 | kingdom \| phylum \| class \| order \| family \| genus \| species
Fungi | GBIF:5 | Basidiomycota | GBIF:34 | Agaricomycetes | GBIF:186 | Agaricales | GBIF:1499 | Agaricaceae | GBIF:4170 | Agaricus | GBIF:2518646 |   |   | Agaricus bisporus | GBIF:5243447 |   |   | Fungi \| Basidiomycota \| Agaricomycetes \| Agaricales \| Agaricaceae \| Agaricus \| Agaricus bisporus | GBIF:5 \| GBIF:34 \| GBIF:186 \| GBIF:1499 \| GBIF:4170 \| GBIF:2518646 \| GBIF:5243447 | kingdom \| phylum \| class \| order \| family \| genus \| species

**Comment by jhpoelen** [comment]
For more context, see associated meeting notes at https://docs.google.com/document/d/1GKU6lc0BN3CFEbZ_VhSTnAOWfiQyjfYBvtUgU7PgfV0 .

**Comment by ljwalker** [comment]
Tested. It works! (As does running against WoRMS.)

**Comment by jhpoelen** [comment]
@ljwalker thanks for checking!

**Comment by jhpoelen** [comment]
@ljwalker I hope that Chrissy and Christina feel listened to, and looking forward to receiving more suggestions.
