### ISSUE TITLE
add DiscoverLife to NAT (name-alignment-template)

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/name-alignment-template#2]
!

**Comment by jhpoelen** [comment]
@seltmann DiscoverLife has been added to name alignment template.

See e.g., https://github.com/Big-Bee-Network/test-name-alignment/runs/7310605398?check_suite_focus=true

```
--- [discoverlife] start ---
[main] INFO org.globalbioticinteractions.nomer.match.TermMatcherRegistry - using matcher [gbif-parse]
[main] INFO org.globalbioticinteractions.nomer.match.TermMatcherRegistry - using matcher [discoverlife-taxon]
real	0m1.216s
user	0m2.240s
sys	0m0.109s
[discoverlife] aligned 14 resolved names to 14 provided names.
[discoverlife] first 10 unresolved names include:
```
For full name alignment report, see attached 
[name-alignment.zip](https://github.com/globalbioticinteractions/name-alignment-template/files/9097023/name-alignment.zip)

**Comment by jhpoelen** [comment]
@seltmann please confirm by closing this issue.

**Comment by jhpoelen** [comment]
@seltmann discoverlife was added to name alignment templates (as well as WFO)
