### ISSUE TITLE
Doubled resolvedName output

### ISSUE THREAD

**Issue by jtmiller28** [globalbioticinteractions/name-alignment-template#3]
For the .txt file generated by the tool, the columns created contain identical names causing confusing labels. There are currently 2 columns named resolvedName, where the second is the fully resolved name output. I'm wondering what the first resolvedName column is for? Is it just removal of characters outside the species name?
![image](https://user-images.githubusercontent.com/82229873/178077204-b4b59df8-49be-4f42-aeaa-c15c08bd3c94.png)
![image](https://user-images.githubusercontent.com/82229873/178077252-a0aaa835-e7af-4239-b436-4128679274ba.png)

**Comment by jtmiller28** [comment]
I think the first column named resolvedName being named parsedName would make sense to me since it would indicate its in the process of being broken down before resolution. That way users can also track through the columns whats occurring and backtrack potential issues that could occur with the first parsing step. The second column that is made with attempted aligned parsed name with nomer is clear with the name resolvedName since this matches previous syntax I've seen like correctedName, alignedName, etc.

**Comment by jhpoelen** [comment]
updated column names to be those listed in 

https://github.com/globalbioticinteractions/globinizer/blob/f9c2096f552b7c5b0adfe5d57ccba5a9700a1a47/align-names.sh#L68

Please re-open / comment / create pull request if you'd like to change the column names.
